// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-ugIl6Kt7X0MtWPFzozptlUlfVIxstg',
    appId: '1:511385905702:web:7884f04e1d40a9731f14e7',
    messagingSenderId: '511385905702',
    projectId: 'perpet-51119',
    authDomain: 'perpet-51119.firebaseapp.com',
    storageBucket: 'perpet-51119.appspot.com',
    measurementId: 'G-G10HZX6GYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrUwWkxL8dtxXiNNttooze2rNPUHEbv9M',
    appId: '1:511385905702:android:9e28c1524afd8f871f14e7',
    messagingSenderId: '511385905702',
    projectId: 'perpet-51119',
    storageBucket: 'perpet-51119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJHLqwyp4A4OBO8NF7GN6gguBDmTaC-ZI',
    appId: '1:511385905702:ios:71ce24f58b914bdf1f14e7',
    messagingSenderId: '511385905702',
    projectId: 'perpet-51119',
    storageBucket: 'perpet-51119.appspot.com',
    iosClientId: '511385905702-hl5mhscvhv54klvq6s1vdllvevhs81gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJHLqwyp4A4OBO8NF7GN6gguBDmTaC-ZI',
    appId: '1:511385905702:ios:71ce24f58b914bdf1f14e7',
    messagingSenderId: '511385905702',
    projectId: 'perpet-51119',
    storageBucket: 'perpet-51119.appspot.com',
    iosClientId: '511385905702-hl5mhscvhv54klvq6s1vdllvevhs81gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpet',
  );
}
