// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgGGWfKeSJLmJFBkDtRTFlro7wrrpvY0',
    appId: '1:980640668438:web:10cc030b00636857a88e37',
    messagingSenderId: '980640668438',
    projectId: 'perpet-e4923',
    authDomain: 'perpet-e4923.firebaseapp.com',
    storageBucket: 'perpet-e4923.appspot.com',
    measurementId: 'G-2MFNQCXY9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGe6f9Pm4KObK-YUl36Fiid4JZKnWNcs4',
    appId: '1:980640668438:android:1eefd88cbb232ba3a88e37',
    messagingSenderId: '980640668438',
    projectId: 'perpet-e4923',
    storageBucket: 'perpet-e4923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7G_qfqoWRbHlYK_f51Tza-ppdsFShFw',
    appId: '1:980640668438:ios:c1e7fa5410d57441a88e37',
    messagingSenderId: '980640668438',
    projectId: 'perpet-e4923',
    storageBucket: 'perpet-e4923.appspot.com',
    iosClientId:
        '980640668438-m01a23oe03k1jbh8mj81lsh0unkbni75.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7G_qfqoWRbHlYK_f51Tza-ppdsFShFw',
    appId: '1:980640668438:ios:c1e7fa5410d57441a88e37',
    messagingSenderId: '980640668438',
    projectId: 'perpet-e4923',
    storageBucket: 'perpet-e4923.appspot.com',
    iosClientId:
        '980640668438-m01a23oe03k1jbh8mj81lsh0unkbni75.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpet',
  );
}
